modLoader = "kotlinforforge"
loaderVersion = "[4.10,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "verdure"
version = "${version}"
displayName = "Verdure Reborn"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.verdure]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.verdure]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.verdure]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
